package com.web.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.web.webservice.ReadMeter;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-28T14:48:49.268+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "ReadMeterImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/AyWebService/webservice/ReadMeter?wsdl",
                  targetNamespace = "http://impl.webservice.web.com/") 
public class ReadMeterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.web.com/", "ReadMeterImplService");
    public final static QName ReadMeterImplPort = new QName("http://impl.webservice.web.com/", "ReadMeterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/AyWebService/webservice/ReadMeter?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReadMeterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/AyWebService/webservice/ReadMeter?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReadMeterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReadMeterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReadMeterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ReadMeterImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReadMeterImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReadMeterImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ReadMeter
     */
    @WebEndpoint(name = "ReadMeterImplPort")
    public ReadMeter getReadMeterImplPort() {
        return super.getPort(ReadMeterImplPort, ReadMeter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReadMeter
     */
    @WebEndpoint(name = "ReadMeterImplPort")
    public ReadMeter getReadMeterImplPort(WebServiceFeature... features) {
        return super.getPort(ReadMeterImplPort, ReadMeter.class, features);
    }

}
